{{- range $.Values.plcs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}-user-config
  labels:
    app.kubernetes.io/part-of: {{ .partOf }}
data: 
  user-config: |
      ;virtuallinux
      [CmpLog]
      Logger.0.Filter=0xFFFFFFFF
      Logger.0.MaxEntries=100000000
      Logger.0.MaxFileSize=1000000000
      CmpWebServer.Filter=0xFFFFFFFF
      CmpOPCUAClient.Filter=0xFFFFFFFF

      [ComponentManager]
      Component.1=CmpBACnet
      Component.2=CmpBACnet2
      Component.3=CmpPLCHandler
      Component.4=CmpGwClient
      Component.5=CmpXMLParser
      Component.6=CmpGwClientCommDrvTcp
      ;Component.7=CmpGwClientCommDrvShm ; enable only if necessary, can result in higher cpu load
      ;Component.8=SysPci				; enable when using Hilscher CIFX
      ;Component.9=CmpHilscherCIFX	; enable when using Hilscher CIFX

      [CmpApp]
      Bootproject.RetainMismatch.Init=1
      RetainType.Applications=InSRAM
      Application.1={{ .appName }}

      [CmpRedundancyConnectionIP]

      [CmpRedundancy]

      [CmpSrv]

      [IoDrvEtherCAT]

      [SysTarget]
      SerialNumber=RTS-{{ .serialNo }}

      [CmpSecureChannel]
      SECURITY.CommunicationMode=ONLY_PLAIN

      [CmpUserMgr]
      AsymmetricAuthKey=0a41d6cf5363d976dce29a300697919b8ece69bd
      SECUTITY.UserMgmtEnforce=NO
      SECURITY.UserMgmtAllowAnonymous=YES

      [CmpSecureChannel]
      CertificateHash=3c0f5865dd0f0fa209668e8f68c2d1341f37a805
  config: |
      ;virtuallinux
      [SysFile]
      FilePath.1=/etc/codesyscontrol/, 3S.dat
      PlcLogicPrefix=1
      
      [SysTarget]
      TargetVersionMask=0
      TargetVersionCompatibilityMask=0xFFFF0000
      
      [CmpSocketCanDrv]
      ScriptPath=/opt/codesys/scripts/
      ScriptName=rts_set_baud.sh
      
      [CmpSettings]
      IsWriteProtected=1
      FileReference.0=SysFileMap.cfg, SysFileMap
      FileReference.1=/conf/codesyscontrol/CODESYSControl_User.cfg
      
      [SysExcept]
      Linux.DisableFpuOverflowException=1
      Linux.DisableFpuUnderflowException=1
      Linux.DisableFpuInvalidOperationException=1
      
      [CmpLog]
      Logger.0.Name=codesyscontrol.log
      ;Logger.0.Filter=0x0000000F ; moved to CODESYSControl_User.cfg to allow changes by PLCShell command
      Logger.0.Enable=1
      Logger.0.MaxEntries=10000000
      Logger.0.MaxFileSize=100000000
      Logger.0.MaxFiles=1
      Logger.0.Backend.0.ClassId=0x0000010B   ;sends logger messages to SysOut
      Logger.0.Backend.1.ClassId=0x00000104   ;writes logger messages in a file
      
      [SysEthernet]
      Linux.ProtocolFilter=3
      
      [CmpSchedule]
      SchedulerInterval=4000
      ProcessorLoad.Enable=1
      ProcessorLoad.Maximum=95
      ProcessorLoad.Interval=5000
      DisableOmittedCycleWatchdog=1
      
      [CmpCodeMeter]
      EnableNetLicenses=1
      InstallCmActContainer=-1
      InstallLegacyCmActContainer=-1
   
  server-ini: |
      [Backup]
      Interval=24
      Path=/var/lib/CodeMeter/Backup
      UpdateCertifiedTime=0
      
      [General]
      ActionTimeIntervall=10
      ApiCommunicationMode=1
      BindAddress=0.0.0.0
      CleanUpTimeOut=120
      CmInstanceUid=0
      CmWANPort=22351
      EnabledContainerTypes=4294967295
      ExePath=/usr/sbin
      HelpFile=/usr/share/doc/CodeMeter
      IsCmWANServer=0
      IsNetworkServer=0
      LogCleanupTimeout=336
      LogCmActDiag=0
      LogLicenseTracking=0
      LogLicenseTrackingPath=/var/log/CodeMeter
      Logging=0
      LogPath=/var/log/CodeMeter
      MaxMessageLen=67108864
      NetworkAccessFsb=0
      NetworkPort=22350
      NetworkTimeout=40
      ProxyPort=0
      ProxyServer=
      ProxyUser=
      UseSystemProxy=1
      StartDaemon=1
      TimeServerTimeout=20
      TimeServerURL1=cmtime.codemeter.com
      TimeServerURL2=cmtime.codemeter.us
      TimeServerURL3=cmtime.codemeter.de
      UDPCachingTime=20
      UDPWaitingTime=1000
      DiagnoseLevel=2
      
      [BorrowClient]
      
      [BorrowServer]
      
      [BorrowManage]
      
      [CmAct\ErrorLogger]
      
      [CmAct\PSNs]
      
      [HTTP]
      DigestAuthentication=0
      RemoteRead=1
      
      [TripleModeRedundancy]
      TmrEnabled=0
      
      [ServerSearchList]
      UseBroadcast=1
  


{{- end }}
