{{- range $.Values.plcs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/part-of: {{ .partOf }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      hostname: {{ .name }}
      volumes:
        - name: data-storage
          persistentVolumeClaim: 
            claimName: {{ .name }}-data
        - name: config
          persistentVolumeCLaim:
            claimName: {{ .name }}-config
        - name: codesys-user-config
          configMap:
            name: {{ .name }}-user-config
            items:
              - key: user-config
                path: CODESYSControl_User.cfg
      initContainers:
      - name: init-plc-application
        image: 'ubi9/ubi-minimal'
        command:
          - sh
          - '-c'
          - mkdir -p /data/codesyscontrol/PlcLogic/{{ .appName }} && cd /data/codesyscontrol/PlcLogic/{{ .appName }} && curl -O {{ .appUrl }}/{{ .appName }}.app && curl -O {{ .appUrl }}/{{ .appName }}.crc && cp -f /temp/conf/CODESYSControl_User.cfg /conf/codesyscontrol/ 
        resources: {}
        volumeMounts:
          - name: data-storage
            mountPath: /data/codesyscontrol
          - name: codesys-user-config
            mountPath: /temp/conf/
          - name: config
            mountPath: /conf/codesyscontrol
      containers:
        - name: codesys-plc
          image: quay.io/rh-ee-hvanniek/codesyscontrol:4.14.0.0
          ports:
            - name: opc-ua
              containerPort: 4840
              protocol: TCP
          volumeMounts:
            - mountPath: "/conf/codesyscontrol/"
              name: config
            - mountPath: "/data/codesyscontrol"
              name: data-storage
