{{- range $.Values.plcs }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/part-of: {{ .partOf }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      hostname: {{ .name }}
      serviceAccountName: codesys-plc-controller-sa
      volumes:
        - name: data-storage
          persistentVolumeClaim: 
            claimName: {{ .name }}-data
        - name: conf-storage
          persistentVolumeClaim:
            claimName: {{ .name }}-config
        - name: codesys-user-config
          configMap:
            name: {{ .name }}-user-config
            items:
              - key: user-config
                path: CODESYSControl_User.cfg
              - key: config
                path: CODESYSControl.cfg
              - key: server-ini
                path: Server.ini
      initContainers:
        - name: init-plc-application
          image: 'ubi9/ubi-minimal'
          securityContext:
            privileged: false
          command:
            - sh
            - '-c'
          args:
            - mkdir -p /data/codesyscontrol/PlcLogic/{{ .appName }}; 
              echo Downloading App from:{{ .appUrl }}; 
              cd /data/codesyscontrol/PlcLogic/{{ .appName }};
              curl -o /data/codesyscontrol/PlcLogic/Application/Application.app {{ .appUrl }}/{{ .appName }}.app; 
              curl -o /data/codesyscontrol/PlcLogic/Application/Application.crc {{ .appUrl }}/{{ .appName }}.crc ;
              mkdir -p /conf/codesyscontrol/ && cd /conf/codesyscontrol;
              echo Copyng files;
              cp -fvLR /temp/conf/* /conf/codesyscontrol/;       
              touch /conf/codesyscontrol/.docker_initialized;
              echo Contents of new conf folder;
              ls /conf/codesyscontrol/ -lah;
              cat /conf/codesyscontrol/CODESYSControl_User.cfg
          resources: {}
          volumeMounts:
            - name: data-storage
              mountPath: /data/codesyscontrol/
            - name: codesys-user-config
              mountPath: /temp/conf/
            - name: conf-storage
              mountPath: /conf/codesyscontrol/
      containers:
        - name: codesys-plc
          image: quay.io/rh-ee-hvanniek/codesyscontrol:4.14.0.0
          securityContext:
            privileged: false
            capabilities:
              add:
                - CAP_CHOWN
                - CAP_IPC_LOCK
                - CAP_KILL
                - CAP_NET_ADMIN
                - CAP_NET_BIND_SERVICE
                - CAP_NET_BROADCAST
                - CAP_NET_RAW
                - CAP_SETFCAP
                - CAP_SETPCAP
                - CAP_SYS_ADMIN
                - CAP_SYS_MODULE
                - CAP_SYS_NICE
                - CAP_SYS_PTRACE
                - CAP_SYS_RAWIO
                - CAP_SYS_RESOURCE
                - CAP_SYS_TIME
          ports:
            - name: opc-ua
              containerPort: 4840
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: ui
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: "/conf/codesyscontrol/"
              name: conf-storage
            - mountPath: "/data/codesyscontrol/"
              name: data-storage
    {{- end }}
