apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-codesys-admin
subjects:
- kind: ServiceAccount
  name: argocd-argocd-application-controller
roleRef:
  kind: Role 
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: privileged-scc-binding
subjects:
  - kind: ServiceAccount
    name: codesys-plc-controller-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: privileged-scc-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: codesys-privileged-binding
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: codesys-plc-controller-sa
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged
