{{- range $.Values.gateway }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/part-of: {{ .partOf }}
spec:
  selector:
    matchLabels:
      app: {{ .name }}
  replicas: 1

  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      hostname: {{ .name }}
      serviceAccountName: codesys-plc-controller-sa
      volumes:
        - name: data-storage
          persistentVolumeClaim: 
            claimName: {{ .name }}-data
        - name: conf-storage
          persistentVolumeClaim:
            claimName: {{ .name }}-config
      containers:
        - name: codesys-gateway
          image: quay.io/rh-ee-hvanniek/codesysgw:4.14.0.0
          ports:
            - name: opc-ua
              containerPort: 1217
              protocol: TCP
          volumeMounts:
            - mountPath: "/conf/codesysedge/"
              name: conf-storage
            - mountPath: "/data/codesysedge/"
              name: data-storage
{{- end }}
